#pragma once
// Calendar feed list, read from /system/calendars.json — written onto the
// SD card by hand, same "not generated by any tool yet in this prototype"
// story as WifiStore.h's wifi.json (see docs/setup-x4.md): ICS feed URLs
// are long, often carry an auth token in the query string, and this
// device has no keyboard for on-device text entry, so there's no on-
// device "add a calendar" flow here either. Read-only from firmware's
// perspective -- never written by this device.

#include <cstddef>

namespace config {

constexpr size_t kMaxCalendars = 4;
constexpr size_t kMaxCalendarUrlLen = 220;
constexpr size_t kMaxCalendarLabelLen = 32;

constexpr const char* kCalendarConfigPath = "/system/calendars.json";

struct CalendarFeed {
  char url[kMaxCalendarUrlLen + 1] = {0};
  char label[kMaxCalendarLabelLen + 1] = {0};  // optional display name, e.g. "Work"
};

class CalendarConfig {
 public:
  static CalendarConfig& instance();

  // Reads /system/calendars.json. A missing or malformed file leaves
  // count() == 0 (not an error) -- calendar sync is opt-in, same as the
  // relay: absent config means "feature not in use," not a fault.
  void load();

  size_t count() const { return count_; }
  const CalendarFeed& at(size_t i) const { return feeds_[i]; }

 private:
  CalendarFeed feeds_[kMaxCalendars];
  size_t count_ = 0;
};

}  // namespace config
